version: "3"
services:
 server:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  restart: unless-stopped
  volumes:
   - ./ConsoleApp1/ConsoleApp1:/ConsoleApp1
   - ./ConsoleApp1/ConsoleApp1.sln:/ConsoleApp1.sln
   - ./Config:/config
  environment:
   PORT: 3018
   HOST: localhost
   NAME: KomischerTyp
   DELAY: 1000
   DIFFICULTY: 5 #0 - 5 (5 is most difficult)
   PATHFINDING: true
  ports:
   - 3018:3018
  command: dotnet run --project ConsoleApp1/ConsoleApp1.csproj
  
